version: '3'

services:
  srs:
    build: 
      context: docker/srs
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # HTTP服务
      - "8000:8000"  # WebRTC
    volumes:
      - ./docker/srs/srs.conf:/usr/local/srs/conf/srs.conf
    restart: always

  signaling:
    build:
      context: .
      dockerfile: docker/signaling/Dockerfile
    ports:
      - "8088:8088"  # WebSocket服务
    environment:
      - NODE_ENV=development
      - PORT=8088
      - MONGODB_URI=mongodb://localhost:27017/live-platform
    depends_on:
      - srs
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./.env:/app/.env
      - ./swagger.yaml:/app/swagger.yaml

    restart: always
