openapi: 3.0.0
info:
  title: Live Platform API
  version: 1.0.0
  description: 直播平台 API 文档
  contact:
    name: API Support
    email: support@example.com
servers:
  - url: http://localhost:3000
    description: 开发环境服务器
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    LoginResponse:
      type: object
      properties:
        token:
          type: string
          description: JWT token
        user:
          type: object
          properties:
            id:
              type: string
            username:
              type: string
            nickname:
              type: string
            avatar_url:
              type: string
            role:
              type: string
              enum:
                - user
                - streamer
                - admin
            last_login_time:
              type: string
              format: date-time
    WebRTCConfig:
      type: object
      properties:
        roomId:
          type: string
          description: 直播间ID
        streamKey:
          type: string
          description: 推流密钥
        webrtcUrl:
          type: string
          description: WebRTC推流地址
        wsUrl:
          type: string
          description: WebSocket信令服务器地址
    StreamStatus:
      type: object
      properties:
        status:
          type: string
          enum:
            - preparing
            - live
            - finished
          description: 直播状态
        startTime:
          type: string
          format: date-time
          description: 开始直播时间
        endTime:
          type: string
          format: date-time
          description: 结束直播时间
    CreateRoomResponse:
      type: object
      properties:
        id:
          type: string
          description: 直播间ID
        title:
          type: string
          description: 直播间标题
        stream_key:
          type: string
          description: 推流密钥
        status:
          type: string
          enum:
            - pending
            - live
            - finished
          description: 直播状态
        user_id:
          type: string
          description: 创建者ID
        created_at:
          type: string
          format: date-time
          description: 创建时间
security:
  - bearerAuth: []
paths:
  /api/auth/login:
    post:
      tags:
        - 认证管理
      summary: 用户名密码登录
      description: 使用用户名和密码进行登录
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                  description: 用户名
                password:
                  type: string
                  format: password
                  description: 密码
      responses:
        '200':
          description: 登录成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '400':
          description: 参数验证失败
        '401':
          description: 密码错误
        '404':
          description: 用户不存在
  /api/rooms:
    post:
      tags:
        - WebRTC直播
      summary: 创建直播间
      description: 创建一个新的直播间
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
              properties:
                title:
                  type: string
                  description: 直播间标题
      responses:
        '200':
          description: 创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRoomResponse'
        '401':
          description: 未授权
        '400':
          description: 参数验证失败
  /api/rooms/{roomId}/rtc-config:
    get:
      tags:
        - WebRTC直播
      summary: 获取直播间WebRTC配置
      description: 获取直播间的WebRTC推流地址和信令服务器地址
      security:
        - bearerAuth: []
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
          description: 直播间ID
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebRTCConfig'
        '404':
          description: 直播间不存在
        '401':
          description: 未授权
  /api/rooms/{roomId}/stream-status:
    get:
      tags:
        - WebRTC直播
      summary: 获取直播流状态
      description: 获取指定直播间的直播状态
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
          description: 直播间ID
      responses:
        '200':
          description: 获取成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamStatus'
        '404':
          description: 直播间不存在
    post:
      tags:
        - WebRTC直播
      summary: 更新直播流状态
      description: 更新指定直播间的直播状态
      security:
        - bearerAuth: []
      parameters:
        - name: roomId
          in: path
          required: true
          schema:
            type: string
          description: 直播间ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - status
              properties:
                status:
                  type: string
                  enum:
                    - live
                    - finished
                  description: 直播状态
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StreamStatus'
        '404':
          description: 直播间不存在
        '401':
          description: 未授权
tags:
  - name: 认证管理
    description: 用户认证相关接口
  - name: WebRTC直播
    description: WebRTC直播相关接口
